### ISSUE TITLE
An error about l2hostility-2.4.13

### ISSUE THREAD

**Issue by Start-Buling** [Minecraft-LightLand/L2Hostility#4]
Hello, sorry to bother you. Just a moment ago, I encountered an error while using your mod.
After starting the game, an error occurs:  java.lang.NoSuchFieldError: EFF_TAGS.
Then I downgraded to version l2hostility-2.4.12, and the game started correctly.
I'm not sure whether to upload reports or logs, so I uploaded both of them.

**reports:**
[crash-2024-01-09_04.08.07-fml.txt](https://github.com/Minecraft-LightLand/L2Hostility/files/13865969/crash-2024-01-09_04.08.07-fml.txt)
**logs:**
[2024-01-09-4.log](https://github.com/Minecraft-LightLand/L2Hostility/files/13866030/2024-01-09-4.log)

**Comment by lcy0x1** [comment]
You need to update L2Complements to use L2Hostility 2.4.13

sorry that I forgot to update the dependency requirement
