### ISSUE TITLE
Hitting causes crash

### ISSUE THREAD

**Issue by YnwLNE** [Minecraft-LightLand/L2Hostility#6]
Tries to blame UnionLib but only crashes when L2Hostility is enabled (I swung on an iron golem which caused it)
Possible incompat?

https://mclo.gs/nnzeKnI

**Comment by lcy0x1** [comment]
They are closed source. Unfortunately I can't see what they does.

Either ask them to open source so that I can check their code, or ask them about what they are trying to do in the event.

**Comment by lcy0x1** [comment]
Any feed back? If not I'm going to close this issue. Feel free to reach out to me in discord

**Comment by Carsonated** [comment]
Mb, life got in the way. I never heard anything back from them and assumed it was going to be continued radio silence. I just removed UnionLib as a whole and all l2 mods are working now

> Any feed back? If not I'm going to close this issue. Feel free to reach out to me in discord
