### ISSUE TITLE
Ticking Entity server crashes which might be related to this mod

### ISSUE THREAD

**Issue by Yowesephth** [Minecraft-LightLand/L2Hostility#7]
I am going off a hunch that these crashes might be related to this mod, mainly on the crashing mob always seeming to have a hostility effect, and the effect going off due to HurtByTargetGoal, which I am aware that the hostility mod adds various effects when a mob is hurt.

https://mclo.gs/SZwdLeN

please let me know what you think and if there's any config I can adjust at the moment to tamper these crashes.

**Comment by lcy0x1** [comment]
It's caused by `Entity::isAllied()` accessing `Entity::getTeam()` while the entity has no team. Try to check if there are any mod altering entity team. If you have more question or want my help to debug the problem join discord and discuss.
